model:
  image_size: 224
  seq_length: 15
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

training:
  batch_size: 4
  epochs: 20
  learning_rate: 0.0001

inference:
  threshold_fake: 0.60
  threshold_real: 0.40